query getSumSubInvestorToken {
    getSumSubInvestorToken
}

query getBlockPassClientID {
    getBlockPassClientID
}

query getNetkiSignUpData {
    getNetkiSignUpData {
        accessCode
        mobileAppPanel
    }
}