INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (18, "Funds Deposited In Wallet");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (19, "Investor Log In");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (20, "Project Administrator Log In");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (21, "Request For Share Purchasing Received");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (22, "Request For Share Purchasing Approved (Blockchain)");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (23, "Request For Share Purchasing Approved (Non-Blockchain)");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (24, "Investor Log Out");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (25, "Project Administrator Log Out");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (26, "Admin Receiving a Payment Request");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (27, "Admin Declining a Payment Request");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (28, "Admin Accepting a Payment Request");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (29, "Trading of Shares Within The Platform (Sell)");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (30, "Trading of Shares Within The Platform (Buy)");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (31, "Contract Signing");
INSERT INTO `activitytype` (`ID`, `Activity`) VALUES (32, "Admin Transferring Shares From an Investor Back to The Company");
